name: Build & Push — AMD64

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 2 1 * *" # chaque 1er du mois à 02h00 UTC
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute version tag
        id: version
        run: |
          TAG=$(date -u +'%Y.%m')
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Build and push (AMD64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-amd64
          platforms: linux/amd64
          push: true
          tags: |
            samtechrepo/focal:amd64-latest
            samtechrepo/focal:amd64-${{ steps.version.outputs.tag }}
          labels: |
            maintainer="Sam Tech Lab"
            org.opencontainers.image.title="Ubuntu Focal base" 
            org.opencontainers.image.description="Base Ubuntu 20.04, légère et sécurisée"
            org.opencontainers.image.version="20.04"
            org.opencontainers.image.architecture=amd64
            org.opencontainers.image.authors="Sam Tech Lab"
            org.opencontainers.image.licenses="MIT"
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.description=Ubuntu base image (AMD64)
            org.opencontainers.image.licenses=MIT
